### ISSUE TITLE
inet_xtoy not installing on mac with m1 processor

### ISSUE THREAD

**Issue by wweaver** [sjinks/node-inet-xtoy#180]
Hello again,

I upgraded to a new mac and now inet_xtoy doesn't seem to install again.

```
% yarn add inet_xtoy --ignore-optional
...
error /Users/wweaver/git/cruise-critic/graphql/services/email-sponsorship/node_modules/inet_xtoy: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi --tag-prefix '' || node-gyp rebuild
Arguments:
Directory: /Users/wweaver/git/cruise-critic/graphql/services/email-sponsorship/node_modules/inet_xtoy
Output:
prebuild-install warn install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.19.1 | darwin | arm64
gyp info find Python using Python version 3.11.2 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wweaver/git/cruise-critic/graphql/services/email-sponsorship/node_modules/inet_xtoy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/wweaver/Library/Caches/node-gyp/14.19.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/wweaver/Library/Caches/node-gyp/14.19.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/wweaver/Library/Caches/node-gyp/14.19.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/wweaver/git/cruise-critic/graphql/services/email-sponsorship/node_modules/inet_xtoy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/wweaver/.nvm/versions/node/v14.19.1/bin/node" "/Users/wweaver/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wweaver/git/cruise-critic/graphql/services/email-sponsorship/node_modules/inet_xtoy
```

From reading this seems like a node-gyp issue more than an inet-xtoy issue but it seems like supposedly it's fixed in node-gyp in future versions. Is it simple enough to just update the dependency on node-gyp? Or should node-gyp be made a real dependency instead of a dev dependency? I'm not sure the solution.

https://github.com/nodejs/node-gyp/issues/2219

**Comment by wweaver** [comment]
Sorry, I found the solution. I did `brew unlink python3` and it reverted the python version back to the system which is python 3.9. Should be good enough for now. Hopefully node-gyp resolves this issue sooner rather than later.
